animals = ['bear', 'python', 'peacock', 'kangaroo', 'whale', 'platypus']
bear = animals[0]

print animals[1]
print animals[4]
print animals[1]
print animals[3]
print animals[6]
print animals[2]
print animals[7]
print animals[4]